In [18]:
import numpy as np
x = np.array(([2,9],[1,5],[3,6]), dtype=float)
y = np.array(([92],[86],[89]), dtype=float)

x = x/np.amax(x)
y = y/100

def sigmoid(x):
    return 1/(1 + np.exp(-x))
#def derivatives_sigmoid(x):
#     return x *(1 - x)


epoch=100 #Setting training iterations
lr=0.1
in_nu = 2
hidd_nu = 4
out_nu = 1

weight_hidd=np.random.uniform(size=(in_nu,hidd_nu))
bias_hidd = np.random.uniform(size=(1,hidd_nu))
weight_out = np.random.uniform(size=(hidd_nu,out_nu))
bias_hidd = np.random.uniform(size=(1,hidd_nu))
bias_out =np.random.uniform(size=(1,out_nu))

for i in range(epoch):
    hidd_in=np.dot(x,weight_hidd) + bias_hidd
    hidd_act = sigmoid(hidd_in)
    out_in=np.dot(hidd_act,weight_out) + bias_out
    out = sigmoid(out_in)
    
print("Input: \n" + str(x))
print("Actual output: \n" + str(y))
print("Predicted output: \n" ,out)

Input: 
[[0.22222222 1.        ]
 [0.11111111 0.55555556]
 [0.33333333 0.66666667]]
Actual output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted output: 
 [[0.89611461]
 [0.88244294]
 [0.88979615]]


In [13]:
weight_hidd=np.random.uniform(size=(in_nu,hidd_nu))
weight_hidd

array([[0.73635479, 0.03369567, 0.97973159, 0.71735053],
       [0.19701449, 0.83671858, 0.57897856, 0.83907264]])

In [10]:
x = np.array(([2,9],[1,5],[3,6]), dtype=float)
x = x/np.amax(x)
x

array([[0.22222222, 1.        ],
       [0.11111111, 0.55555556],
       [0.33333333, 0.66666667]])

In [11]:
y = np.array(([92],[86],[89]), dtype=float) 
y = y/np.amax(y)
y

array([[1.        ],
       [0.93478261],
       [0.9673913 ]])